install.packages(c(
  "bs4Dash",
  "corrr",
  "fst",
  "keras",
  "lobstr",
  "pingr",
  "pryr",
  "qs",
  "recipes",
  "remotes",
  "rmarkdown",
  "rprojroot",
  "rsample",
  "shiny",
  "shinycssloaders",
  "tidyverse",
  "usethis",
  "visNetwork",
  "yardstick"
))
renv::install("rstudio/reticulate")
renv::install("ropensci/targets")
renv::install("ropensci/tarchetypes")
reticulate::install_miniconda()
keras::install_keras()
